name: release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # build takes ~1 min, publish takes ~7 min; however can be "pending" for ~5 min. https://central.sonatype.com/publishing
    steps:
      - uses: actions/checkout@v4

        # https://www.linkedin.com/pulse/uploading-artifacts-maven-central-github-actions-itemis/
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin # https://github.com/actions/setup-java#supported-distributions
          java-package: jdk
          cache: maven
          check-latest: true
          server-id: central
          server-username: SONATYPE_USER
          server-password: SONATYPE_PW
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: SIGN_KEY_PASS # Env var that holds the key's passphrase

            # this thing is so slow we are already past the 2ndary rate limit window
      - name: pause to avoid 2ndary rate limits # https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits
        run: |
          sleep 1

      - uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
